server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      - id: ms-mpesa-service
        uri: http://localhost:8082/
        predicates:
          - Path=/api/v1/mpesa/**

      - id: ms-queue-with-rabbitMQ
        uri: http://localhost:8081/
        predicates:
          - Path=/order/**
t



